"use client";

import { useEffect, useState } from "react";
import AskTrendAi from "@/components/AskTrendAi";
import DigestBanner from "@/components/DigestBanner";
import PresenceBadge from "@/components/PresenceBadge";
import TrendCard from "@/components/TrendCard";
import TrendTimeline from "@/components/TrendTimeline";
import TrendingTicker from "@/components/TrendingTicker";

type Trend = { id?: number; term: string; source: string; score?: number | null; title?: string | null; summary?: string | null; url?: string | null; ticker?: string | null; category?: string | null; scope?: string | null; };
type PhilippinesStory = { id: number; title: string; summary: string | null; url: string; source: string | null; category: string | null; };
const watchKey = (trend: Trend) => String(trend.id ?? trend.url ?? trend.term);
const topicKey = (trend: Trend) => {
  const text = `${trend.title || ""} ${trend.term}`.toLowerCase();
  const namedTopics = ["macbook", "iphone", "ipad", "apple", "openai", "chatgpt", "anthropic", "claude", "gemini", "nvidia", "amd", "intel", "microsoft", "google", "android", "tesla", "cybersecurity", "semiconductor", "robot"];
  return namedTopics.find((topic) => text.includes(topic)) || text.replace(/[^a-z0-9]+/g, " ").trim();
};
const AI_TECH_TERMS = /\b(ai|artificial intelligence|chatgpt|openai|anthropic|claude|gemini|iphone|ipad|macbook|apple|android|samsung|galaxy|nvidia|amd|intel|semiconductor|chip|robot|cybersecurity|software|technology|tech)\b/i;
const isAiOrTech = (trend: Trend) => ["ai", "tech"].includes(trend.category?.toLowerCase() || "") || AI_TECH_TERMS.test(`${trend.title || ""} ${trend.term}`);
const hasEnglishTickerLabel = (trend: Trend) => /^[\x00-\x7F]*$/.test(trend.title || trend.term);

export default function FeedClient({ initialTrending, digestContent, digestGeneratedAt, globalDigestContent, globalDigestGeneratedAt, analyzedNews }: { initialArticles: unknown[]; initialTrending: Trend[]; backendReachable: boolean; digestContent: string | null; digestGeneratedAt: string | null; globalDigestContent: string | null; globalDigestGeneratedAt: string | null; analyzedNews: PhilippinesStory[]; }) {
  const [selectedTrend, setSelectedTrend] = useState<Trend | null>(null);
  const [watched, setWatched] = useState<string[]>([]);
  useEffect(() => { setWatched(JSON.parse(window.localStorage.getItem("trend-ai-watchlist") || "[]")); }, []);
  const toggleWatch = (trend: Trend) => setWatched((current) => { const key = watchKey(trend); const next = current.includes(key) ? current.filter((item) => item !== key) : [...current, key]; window.localStorage.setItem("trend-ai-watchlist", JSON.stringify(next)); return next; });
  const globalCards = initialTrending.filter((trend) => trend.scope === "global" && isAiOrTech(trend)).map((trend) => ({ ...trend, category: trend.category?.toLowerCase() === "ai" ? "AI" : "Tech" })).slice(0, 8);
  const globalTopics = new Set(globalCards.map(topicKey));
  const tickerTrends = initialTrending.filter((trend) => isAiOrTech(trend) && hasEnglishTickerLabel(trend) && !globalTopics.has(topicKey(trend))).filter((trend, index, terms) => terms.findIndex((candidate) => topicKey(candidate) === topicKey(trend)) === index).slice(0, 12);
  const followed = globalCards.filter((trend) => watched.includes(watchKey(trend)));
  return <><nav aria-label="Page sections" className="sticky top-0 z-10 border-b px-6 py-3" style={{ background: "var(--paper)", borderColor: "var(--line)" }}><div className="max-w-6xl mx-auto flex flex-wrap items-center gap-x-5 gap-y-2 font-mono text-xs"><a href="#top" className="font-semibold" style={{ color: "var(--coral)" }}>TREND.AI</a><a href="#global-signals" className="hover:underline">Global Signals</a><a href="#momentum" className="hover:underline">Momentum</a><a href="#ask-trend-ai" className="hover:underline">Ask Trend.AI</a><a href="#news" className="hover:underline">Philippines Today</a></div></nav><TrendingTicker terms={tickerTrends} onTermClick={setSelectedTrend} /><main id="top" className="max-w-6xl mx-auto px-6 py-10">
    <header className="mb-10"><p className="font-mono text-xs uppercase tracking-[0.2em] mb-3" style={{ color: "var(--coral)" }}>Signal over noise</p><div className="max-w-3xl"><h1 className="font-display text-5xl font-semibold mb-3">Trend.ai</h1><p className="text-lg opacity-70 leading-relaxed">A clearer view of the stories shaping today.</p></div></header>
    <PresenceBadge />
    {followed.length > 0 && <section className="mb-8 border rounded-sm p-4" style={{ borderColor: "var(--line)" }}><p className="font-mono text-xs opacity-50 mb-2">YOUR WATCHLIST</p><div className="flex flex-wrap gap-2">{followed.map((trend) => <button key={watchKey(trend)} onClick={() => setSelectedTrend(trend)} className="rounded-full border px-3 py-1 font-mono text-xs" style={{ borderColor: "var(--line)" }}>{trend.ticker || trend.title || trend.term}</button>)}</div></section>}
    {selectedTrend && <section className="mb-12 border-l-4 p-6" style={{ borderColor: "var(--coral)", background: "rgba(232, 93, 78, 0.06)" }} aria-live="polite"><div className="flex items-start justify-between gap-4"><div><p className="font-mono text-xs mb-2" style={{ color: "var(--coral)" }}>SOURCE BRIEF · {selectedTrend.category || "TREND"}</p><h2 className="font-display text-3xl mb-3">{selectedTrend.title || selectedTrend.term}</h2></div><button onClick={() => setSelectedTrend(null)} className="font-mono text-xs opacity-60">Close ×</button></div><p className="max-w-3xl leading-relaxed text-lg">{selectedTrend.summary || "A verified brief is being prepared from the publisher's reporting. Open the original source for the latest details."}</p>{selectedTrend.url && <a className="inline-block mt-4 font-mono text-xs" style={{ color: "var(--manila-blue)" }} href={selectedTrend.url} target="_blank" rel="noopener noreferrer">Read the reporting source →</a>}</section>}
    <section id="global-signals" className="mb-12 scroll-mt-16" aria-label="Trending Now in AI and Tech"><div className="flex items-end justify-between gap-4 mb-5"><div><p className="font-mono text-xs opacity-50 mb-1">GLOBAL SIGNALS</p><h2 className="font-display text-3xl">Trending Now in AI &amp; Tech</h2></div><span className="font-mono text-xs opacity-50">English · source brief on click</span></div><DigestBanner content={globalDigestContent} generatedAt={globalDigestGeneratedAt} title="Summary of Global Signals" emptyMessage="The global AI and technology briefing appears after the next refresh." />{globalCards.length ? <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">{globalCards.map((trend) => <TrendCard key={watchKey(trend)} trend={{ ...trend, title: trend.title || trend.term, summary: trend.summary || "A fact brief is being prepared from the publisher's reporting.", url: trend.url || null, ticker: trend.ticker || null, category: trend.category || null, scope: "global" }} isWatched={watched.includes(watchKey(trend))} onToggleWatch={toggleWatch} />)}</div> : <div className="border rounded-sm p-5 text-sm opacity-60" style={{ borderColor: "var(--line)" }}>Run the global refresh once to load and enrich AI and Tech briefs.</div>}</section>
    <div id="momentum" className="scroll-mt-16"><TrendTimeline /></div><div id="ask-trend-ai" className="scroll-mt-16"><AskTrendAi /></div>
    <section id="news" className="mb-12 scroll-mt-16" aria-label="What is happening in the Philippines today"><div className="mb-5"><p className="font-mono text-xs opacity-50 mb-1">PHILIPPINES TODAY</p><h2 className="font-display text-3xl">What&apos;s happening in the Philippines today</h2><p className="mt-2 text-sm opacity-65">A clear summary of the important stories unfolding across the Philippines today.</p></div><DigestBanner content={digestContent} generatedAt={digestGeneratedAt} />{analyzedNews.length ? <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">{analyzedNews.map((story) => <TrendCard key={story.id} trend={{ term: story.title, title: story.title, summary: story.summary, url: story.url, ticker: null, category: story.category, source: story.source || "Philippines news", scope: "philippines" }} />)}</div> : <div className="border rounded-sm p-5 text-sm opacity-60" style={{ borderColor: "var(--line)" }}>Today&apos;s Philippines summary appears once five fresh stories are available.</div>}</section>
  </main></>;
}
