"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-16

Creates the Phase 1 tables: sources, categories, clusters, articles,
trending_terms, digests. Also enables the pgvector extension required
for the articles.embedding column.

Hand-written rather than autogenerated (no live DB in this environment
to diff against) — double check against app/models/schema.py before
running on a real database, and prefer regenerating with
`alembic revision --autogenerate` once you have a dev DB connected.
"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None

EMBEDDING_DIM = 768


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table(
        "sources",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("name", sa.String, nullable=False, unique=True),
        sa.Column("feed_url", sa.String, nullable=False),
        sa.Column("created_at", sa.DateTime, server_default=sa.func.now()),
    )

    op.create_table(
        "categories",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("name", sa.String, nullable=False, unique=True),
    )

    op.create_table(
        "clusters",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("representative_title", sa.String),
        sa.Column("created_at", sa.DateTime, server_default=sa.func.now()),
    )

    op.create_table(
        "articles",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("title", sa.String, nullable=False),
        sa.Column("summary", sa.Text),
        sa.Column("raw_summary", sa.Text),
        sa.Column("url", sa.String, nullable=False, unique=True),
        sa.Column("published_at", sa.DateTime),
        sa.Column("ingested_at", sa.DateTime, server_default=sa.func.now()),
        sa.Column("source_id", sa.Integer, sa.ForeignKey("sources.id")),
        sa.Column("category_id", sa.Integer, sa.ForeignKey("categories.id"), nullable=True),
        sa.Column("cluster_id", sa.Integer, sa.ForeignKey("clusters.id"), nullable=True),
        sa.Column("embedding", Vector(EMBEDDING_DIM), nullable=True),
    )
    op.create_index("ix_articles_published_at", "articles", ["published_at"])

    op.create_table(
        "trending_terms",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("term", sa.String, nullable=False),
        sa.Column("source", sa.String, nullable=False),
        sa.Column("score", sa.Integer, nullable=True),
        sa.Column("captured_at", sa.DateTime, server_default=sa.func.now()),
    )

    op.create_table(
        "digests",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("content", sa.Text, nullable=False),
        sa.Column("generated_at", sa.DateTime, server_default=sa.func.now()),
    )


def downgrade():
    op.drop_table("digests")
    op.drop_table("trending_terms")
    op.drop_index("ix_articles_published_at", table_name="articles")
    op.drop_table("articles")
    op.drop_table("clusters")
    op.drop_table("categories")
    op.drop_table("sources")
